apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lgilpin-clevr-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-ceph-block